---
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME=template_role
  matrix:
    - MOLECULE_DISTRO: ubuntu1804

before_install:
cache: pip
install:
  - sudo apt-get -qq update
  - pip install molecule docker

before_script:

script:
  - ansible --version
  - molecule --version
  - echo "${MOLECULE_DISTRO}"
  - molecule test -s "travisci_${MOLECULE_DISTRO}"
