---
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME=template_role

before_install:
cache: pip
  - sudo apt-get -qq update
install:
  - pip install molecule docker

before_script:

script:
  - molecule test -s travisci
