---

- name: Install template_role_extra_packages
  apt:
    name: "{{ template_role_extra_packages }}"
    state: present

- name: Install template_role_package
  apt:
    name: "{{ template_role_package }}"
    state: present
