---

- name: Install blackbox_exporter_extra_packages
  apt:
    name: "{{ blackbox_exporter_extra_packages }}"
    state: present

- name: Install blackbox_exporter_package
  apt:
    name: "{{ blackbox_exporter_package }}"
    state: present

- name: "Enable blackbox_exporter_service {{ blackbox_exporter_service }}"
  service:
    name: "{{ blackbox_exporter_service }}"
    enabled: yes

- name: "Create /etc/default/{{ blackbox_exporter_service }}"
  template:
    src: Debian.default.j2
    dest: "/etc/default/{{ blackbox_exporter_service }}"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart blackbox_exporter_service
