---

- name: Install blackbox_exporter_extra_packages
  pkgng:
    name: "{{ blackbox_exporter_extra_packages }}"
    state: present

- name: Install blackbox_exporter_package
  pkgng:
    name: "{{ blackbox_exporter_package }}"
    state: present

- name: Enable blackbox_exporter_service
  service:
    name: "{{ blackbox_exporter_service }}"
    enabled: yes

- name: "Create /etc/rc.conf.d/{{ blackbox_exporter_service }}"
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ blackbox_exporter_service }}"
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart blackbox_exporter_service
