---

- name: Install template_role_extra_packages
  openbsd_pkg:
    name: "{{ template_role_extra_packages }}"
    state: present

- name: Install template_role_package
  openbsd_pkg:
    name: "{{ template_role_package }}"
    state: present
