---

- name: Install template_role_extra_packages
  yum:
    name: "{{ template_role_extra_packages }}"
    state: present

- name: Install template_role_package
  yum:
    name: "{{ template_role_package }}"
    state: present

- name: Enable template_role_service
  service:
    name: "{{ template_role_service }}"
    enabled: yes
    use: "{% if ansible_os_family == 'RedHat' and ansible_distribution_version is version('7.7', '>=') %}systemd{% else %}default(omit){% endif %}"

- name: "Create /etc/sysconfig/{{ template_role_service }}"
  template:
    src: RedHat.sysconfig.j2
    dest: "/etc/sysconfig/{{ template_role_service }}"
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart template_role_service
