---

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: "Create {{ blackbox_exporter_config_dir }}"
  file:
    path: "{{ blackbox_exporter_config_dir }}"
    state: directory

- name: "Create {{ blackbox_exporter_config_file }}"
  template:
    src: blackbox_exporter.yml.j2
    dest: "{{ blackbox_exporter_config_file }}"
  notify:
    - Restart blackbox_exporter_service

- name: "Add blackbox_exporter_user to blackbox_exporter_extra_groups"
  user:
    name: "{{ blackbox_exporter_user }}"
    append: yes
    create_home: no
    groups: "{{ blackbox_exporter_extra_groups }}"

- name: Create blackbox_exporter_log_dir
  file:
    path: "{{ blackbox_exporter_log_dir }}"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    mode: 0755
    state: directory
  when:
    # XXX ubuntu package does not log to a file, but to /var/log/syslog
    - ansible_os_family != 'Debian'

- name: Start blackbox_exporter_service
  service:
    name: "{{ blackbox_exporter_service }}"
    state: started
