---

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: "Create {{ template_role_config_dir }}"
  file:
    path: "{{ template_role_config_dir }}"
    state: directory

- name: "Create {{ template_role_config_file }}"
  template:
    src: template_role.conf.j2
    dest: "{{ template_role_config_file }}"
  notify:
    - Restart template_role_service

- name: Start template_role_service
  service:
    name: "{{ template_role_service }}"
    state: started
    use: "{% if ansible_os_family == 'RedHat' and ansible_distribution_version is version('7.7', '>=') %}systemd{% else %}default(omit){% endif %}"
