---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: openbsd-6.5
    box: trombik/ansible-openbsd-6.5-amd64
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  become: True
  options:
    v: True
    become: True
  config_options:
    defaults:
      retry_files_enabled: false
      stdout_callback: yaml
  playbooks:
    prepare: ../resources/playbooks/playbook.yml
    converge: ../resources/playbooks/playbook.yml
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
