---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: instance
    box: trombik/ansible-freebsd-12.0-amd64
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  become: true
  options:
    become: true
  config_options:
    defaults:
      retry_files_enabled: false
      stdout_callback: yaml
  playbooks:
    prepare: ../resources/playbooks/playbook.yml
    converge: ../resources/playbooks/playbook.yml
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
