---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: centos7
    hostname: centos7
    image: geerlingguy/docker-centos7-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

lint:
  name: yamllint

provisioner:
  name: ansible
  become: True
  options:
    v: True
    become: True
  config_options:
    defaults:
      retry_files_enabled: false
      stdout_callback: yaml
  playbooks:
    prepare: ../resources/playbooks/playbook.yml
    converge: ../resources/playbooks/playbook.yml
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
