---
- name: Converge
  hosts: all
  roles:
    - role: trombik.template_role
  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
    - name: List all services (systemd)
      # workaround ansible-lint: [303] service used in place of service module
      shell: "echo; systemctl list-units --type service"
      when:
        - ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
    - name: list all services (FreeBSD service)
      # workaround ansible-lint: [303] service used in place of service module
      shell: "echo; service -l"
      when:
        - ansible_os_family == 'FreeBSD'
    - name: list all services (rcctl)
      command: "rcctl ls all"
      when:
        - ansible_os_family == 'OpenBSD'


  vars:
    os_template_role_flags:
      OpenBSD: -4
      FreeBSD: ""
      Debian: ""
      RedHat: ""
    os_port:
      OpenBSD: 10022
      FreeBSD: 10022
      Debian: 10022
      RedHat: 22
    template_role_flags: "{{ os_template_role_flags[ansible_os_family] }}"
    # on RedHat, non-default port is not allowed to listen on
    # on FreeBSD, sshd from the base and one from the package are both running
    template_role_config: |
      UseDNS no
      Port {{ os_port[ansible_os_family] }}
      {% if ansible_os_family != 'FreeBSD' and ansible_os_family != 'RedHat' %}
      Port 22
      {% endif %}
